### ISSUE TITLE
Run test

### ISSUE THREAD

**Issue by llooFlashooll** [bltlab/seqscore#2]
Dear author,
I don't know how to run test cases for scoring after I configure according to the document.
When I type:
``` seqscore score prediction_conll_file --reference reference_conll_file ```
it just report errors like this:
``` 
Traceback (most recent call last):
  File "e:\anaconda\envs\seqscore\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "e:\anaconda\envs\seqscore\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\Anaconda\envs\seqscore\Scripts\seqscore.exe\__main__.py", line 7, in <module>
  File "e:\anaconda\envs\seqscore\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "e:\anaconda\envs\seqscore\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "e:\anaconda\envs\seqscore\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "e:\anaconda\envs\seqscore\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "e:\anaconda\envs\seqscore\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "e:\anaconda\envs\seqscore\lib\site-packages\seqscore\scripts\seqscore.py", line 117, in score
    score_conll_files(
  File "e:\anaconda\envs\seqscore\lib\site-packages\seqscore\conll.py", line 287, in score_conll_files
    pred_docs = ingest_conll_file(
  File "e:\anaconda\envs\seqscore\lib\site-packages\seqscore\conll.py", line 229, in ingest_conll_file
    with open(input_path, encoding="utf8") as input_file:
FileNotFoundError: [Errno 2] No such file or directory: 'prediction_conll_file'
```
How can I run your model?

**Comment by ConstantineLignos** [comment]
Sorry, for some reason I didn't get a notification about this issue being opened. When you're scoring, you need two files, the reference and your system output. In your case you are specifying `prediction_conll_file` as the system output, and `reference_conll_file` as the reference. Are those the actual paths to those files on your computer? The error message is telling you that there is no file called `prediction_conll_file` in that directory at least.

**Comment by llooFlashooll** [comment]
I see. Thank you for your reply!
